Allow and deny list
NCATSTranslator/workflow-runner pull request #35
Opened 2022-03-21 20:49 UTC by uhbrar

This implements the usage of the allow and deny list as discussed by the Operations and Workflows Working Group.

Currently, this utilizes the SmartAPI title for the service, as discussed during the last working group meeting. Before merging, it should be decided whether this is really the route to take, or whether or not it is more appropriate to use infores identifiers.

2022-05-18 19:57 UTC, kennethmorton requested changes

2022-05-18 19:57 UTC, kennethmorton commented on app/server.py
> +                for service in SERVICES[operation["id"]]:
We need a safety check here that operation["id"] is present in SERVICES. #36

2022-05-18 19:57 UTC, kennethmorton commented on app/server.py
> +                for service in SERVICES[operation["id"]]:
Same here

2022-05-18 19:57 UTC, kennethmorton commented on app/server.py
> +            for service in operation_services:
We should have a check prior to this line that we actually have any operation_services. If we don't we should send something helpful. See #36

2022-05-18 19:57 UTC, kennethmorton commented on requirements-lock.txt
> +reasoner-pydantic==2.2.1
A new version of reasoner-pydantic will be out very soon. We might want to wait to merge this until after upgrading.

2022-05-18 19:57 UTC, kennethmorton commented on requirements.txt
> +reasoner-pydantic==2.2.1
Wait for new version. See above.

2022-05-19 14:59 UTC, uhbrar commented
I think it would be best to address these issues in a separate branch, for tracking purposes. This pull request is an enhancement. I plan on creating a separate pull request to handle bug fixes.

2022-05-19 16:03 UTC, kennethmorton commented
Fair enough.

2022-05-19 16:04 UTC, merged